// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eg_mu.Models;

#nullable disable

namespace eg_mu.Migrations
{
    [DbContext(typeof(GrandEgyptianContext))]
    [Migration("20260119215142_updateDataAssign")]
    partial class updateDataAssign
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eg_mu.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AdminID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId")
                        .HasName("PK__Admins__719FE4E89CBE3E34");

                    b.HasIndex(new[] { "Email" }, "UQ__Admins__A9D10534651BC863")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("eg_mu.Models.Artifact", b =>
                {
                    b.Property<int>("ArtifactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ArtifactID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtifactId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Era")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImageURL");

                    b.Property<int?>("LabId")
                        .HasColumnType("int")
                        .HasColumnName("LabID");

                    b.Property<string>("Material")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("SectionID");

                    b.HasKey("ArtifactId")
                        .HasName("PK__Artifact__E788EA9606BA700C");

                    b.HasIndex("LabId");

                    b.HasIndex("SectionId");

                    b.ToTable("Artifacts");
                });

            modelBuilder.Entity("eg_mu.Models.ArtifactsExhibition", b =>
                {
                    b.Property<int>("ArtifactId")
                        .HasColumnType("int")
                        .HasColumnName("ArtifactID");

                    b.Property<int>("ExhibitionId")
                        .HasColumnType("int")
                        .HasColumnName("ExhibitionID");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ImageURL");

                    b.HasKey("ArtifactId", "ExhibitionId")
                        .HasName("PK__Artifact__14A43651826F0E4A");

                    b.HasIndex("ExhibitionId");

                    b.ToTable("ArtifactsExhibitions");
                });

            modelBuilder.Entity("eg_mu.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AttendanceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateTime?>("CheckIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<TimeSpan>("CheckInTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("datetime");

                    b.Property<TimeSpan>("CheckOutTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("StaffID");

                    b.HasKey("AttendanceId")
                        .HasName("PK__Attendan__8B69263CEF699885");

                    b.HasIndex("StaffId");

                    b.ToTable("Attendance", (string)null);
                });

            modelBuilder.Entity("eg_mu.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("AgeCategory")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("BookingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Nationality")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PriceId")
                        .HasColumnType("int")
                        .HasColumnName("PriceID");

                    b.Property<int?>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly>("VisitDate")
                        .HasColumnType("date");

                    b.Property<int>("VisitorId")
                        .HasColumnType("int")
                        .HasColumnName("VisitorID");

                    b.HasKey("BookingId")
                        .HasName("PK__Bookings__73951ACD8464F14E");

                    b.HasIndex("PriceId");

                    b.HasIndex("VisitorId");

                    b.ToTable("Bookings", t =>
                        {
                            t.HasTrigger("trg_CalculateTotal");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("eg_mu.Models.ConservationLab", b =>
                {
                    b.Property<int>("LabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LabID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabId"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ImageURL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("SectionID");

                    b.HasKey("LabId")
                        .HasName("PK__Conserva__EDBD773A2BE53AA7");

                    b.HasIndex("SectionId");

                    b.ToTable("ConservationLabs");
                });

            modelBuilder.Entity("eg_mu.Models.DailyTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TaskID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<DateTime>("DateAssigned")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("StaffID");

                    b.Property<DateOnly?>("TaskDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskId")
                        .HasName("PK__DailyTas__7C6949D119972A8D");

                    b.HasIndex("StaffId");

                    b.ToTable("DailyTasks");
                });

            modelBuilder.Entity("eg_mu.Models.Exhibition", b =>
                {
                    b.Property<int>("ExhibitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ExhibitionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExhibitionId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ImageURL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("SectionID");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("ExhibitionId")
                        .HasName("PK__Exhibiti__32CDCC7EEC518E2C");

                    b.HasIndex("SectionId");

                    b.ToTable("Exhibitions");
                });

            modelBuilder.Entity("eg_mu.Models.Garden", b =>
                {
                    b.Property<int>("GardenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GardenID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GardenId"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ImageURL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("SectionID");

                    b.HasKey("GardenId")
                        .HasName("PK__Gardens__0191D063819C7315");

                    b.HasIndex("SectionId");

                    b.ToTable("Gardens");
                });

            modelBuilder.Entity("eg_mu.Models.MuseumSection", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SectionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectionId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SectionId")
                        .HasName("PK__MuseumSe__80EF08927B905AA5");

                    b.ToTable("MuseumSections");
                });

            modelBuilder.Entity("eg_mu.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StaffID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("HireDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("SectionID");

                    b.HasKey("StaffId")
                        .HasName("PK__Staff__96D4AAF7F933DF4A");

                    b.HasIndex("SectionId");

                    b.HasIndex(new[] { "Email" }, "UQ__Staff__A9D10534DD440527")
                        .IsUnique();

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("eg_mu.Models.TicketPrice", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PriceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("PriceId")
                        .HasName("PK__TicketPr__4957584FDE104E7D");

                    b.ToTable("TicketPrices");
                });

            modelBuilder.Entity("eg_mu.Models.Visitor", b =>
                {
                    b.Property<int>("VisitorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VisitorID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitorId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VisitorId")
                        .HasName("PK__Visitors__B121AFA825C4740C");

                    b.HasIndex(new[] { "Email" }, "UQ__Visitors__A9D10534558396D0")
                        .IsUnique();

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("eg_mu.Models.Artifact", b =>
                {
                    b.HasOne("eg_mu.Models.ConservationLab", "Lab")
                        .WithMany("Artifacts")
                        .HasForeignKey("LabId")
                        .HasConstraintName("FK_Artifacts_ConservationLabs");

                    b.HasOne("eg_mu.Models.MuseumSection", "Section")
                        .WithMany("Artifacts")
                        .HasForeignKey("SectionId")
                        .IsRequired()
                        .HasConstraintName("FK_Artifacts_Sections");

                    b.Navigation("Lab");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("eg_mu.Models.ArtifactsExhibition", b =>
                {
                    b.HasOne("eg_mu.Models.Artifact", "Artifact")
                        .WithMany("ArtifactsExhibitions")
                        .HasForeignKey("ArtifactId")
                        .IsRequired()
                        .HasConstraintName("FK__Artifacts__Artif__6477ECF3");

                    b.HasOne("eg_mu.Models.Exhibition", "Exhibition")
                        .WithMany("ArtifactsExhibitions")
                        .HasForeignKey("ExhibitionId")
                        .IsRequired()
                        .HasConstraintName("FK__Artifacts__Exhib__656C112C");

                    b.Navigation("Artifact");

                    b.Navigation("Exhibition");
                });

            modelBuilder.Entity("eg_mu.Models.Attendance", b =>
                {
                    b.HasOne("eg_mu.Models.Staff", "Staff")
                        .WithMany("Attendances")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK_Attendance_Staff");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("eg_mu.Models.Booking", b =>
                {
                    b.HasOne("eg_mu.Models.TicketPrice", "Price")
                        .WithMany("Bookings")
                        .HasForeignKey("PriceId")
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Prices");

                    b.HasOne("eg_mu.Models.Visitor", "Visitor")
                        .WithMany("Bookings")
                        .HasForeignKey("VisitorId")
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Visitors");

                    b.Navigation("Price");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("eg_mu.Models.ConservationLab", b =>
                {
                    b.HasOne("eg_mu.Models.MuseumSection", "Section")
                        .WithMany("ConservationLabs")
                        .HasForeignKey("SectionId")
                        .IsRequired()
                        .HasConstraintName("FK_ConservationLabs_Sections");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("eg_mu.Models.DailyTask", b =>
                {
                    b.HasOne("eg_mu.Models.Staff", "Staff")
                        .WithMany("DailyTasks")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK_Tasks_Staff");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("eg_mu.Models.Exhibition", b =>
                {
                    b.HasOne("eg_mu.Models.MuseumSection", "Section")
                        .WithMany("Exhibitions")
                        .HasForeignKey("SectionId")
                        .IsRequired()
                        .HasConstraintName("FK_Exhibitions_Sections");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("eg_mu.Models.Garden", b =>
                {
                    b.HasOne("eg_mu.Models.MuseumSection", "Section")
                        .WithMany("Gardens")
                        .HasForeignKey("SectionId")
                        .HasConstraintName("FK_Gardens_Sections");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("eg_mu.Models.Staff", b =>
                {
                    b.HasOne("eg_mu.Models.MuseumSection", "Section")
                        .WithMany("Staff")
                        .HasForeignKey("SectionId")
                        .HasConstraintName("FK_Staff_Sections");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("eg_mu.Models.Artifact", b =>
                {
                    b.Navigation("ArtifactsExhibitions");
                });

            modelBuilder.Entity("eg_mu.Models.ConservationLab", b =>
                {
                    b.Navigation("Artifacts");
                });

            modelBuilder.Entity("eg_mu.Models.Exhibition", b =>
                {
                    b.Navigation("ArtifactsExhibitions");
                });

            modelBuilder.Entity("eg_mu.Models.MuseumSection", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("ConservationLabs");

                    b.Navigation("Exhibitions");

                    b.Navigation("Gardens");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("eg_mu.Models.Staff", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("DailyTasks");
                });

            modelBuilder.Entity("eg_mu.Models.TicketPrice", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("eg_mu.Models.Visitor", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
